# Generated by Django 5.2.4 on 2025-07-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='username',
            field=models.CharField(blank=True, help_text='Optional, 255 charachters or fewer', max_length=255, null=True, unique=True),
        ),
    ]
