# Generated by Django 5.2.4 on 2025-07-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_baseuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='username',
            field=models.CharField(default=3, help_text='Optional, 255 charachters or fewer', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
