# Generated by Django 5.2.4 on 2025-07-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_baseuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
