# Generated by Django 5.2.4 on 2025-07-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_recruiterprofile_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='photo',
            field=models.ImageField(blank=True, default='profiles/default.svg', null=True, upload_to='profiles/%y/%m/%d'),
        ),
    ]
