# Generated by Django 5.2.4 on 2025-07-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
