# Generated by Django 5.2.4 on 2025-07-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
