# Generated by Django 5.2.4 on 2025-07-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='price',
            field=models.PositiveBigIntegerField(),
        ),
    ]
