# Generated by Django 5.2.4 on 2025-07-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(default='N/A', max_length=155),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(default='Full-time', max_length=155),
        ),
    ]
