# Generated by Django 5.2.4 on 2025-07-14 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_experience_job_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('whatsapp', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('education', models.CharField(choices=[('high_school', 'High School'), ('undergraduate', 'Undergraduate Student'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD')], max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('other_language_1', models.CharField(blank=True, max_length=50, null=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Candidate Application',
                'verbose_name_plural': 'Candidate Applications',
                'ordering': ['-application_date'],
            },
        ),
    ]
