# Generated by Django 5.2.4 on 2025-07-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_candidatedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedetails',
            name='other_language_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidatedetails',
            name='education',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate Student'), ('graduate', 'Graduate')], max_length=20),
        ),
    ]
