# Generated by Django 5.2.4 on 2025-07-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_candidatedetails_other_language_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedetails',
            name='status',
            field=models.CharField(default='pending'),
        ),
    ]
