# Generated by Django 5.2.4 on 2025-07-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_candidatedetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedetails',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
