# Generated by Django 5.2.4 on 2025-07-13 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tmonials',
            options={'verbose_name': 'Testimonial'},
        ),
    ]
